name: Prepare CSV of amounts

on:
  schedule:
    - cron: "20,40 * * * *" # every 20 and 40th minute

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run scraper
        id: scraper
        run: ./format.sh

      - name: Commit to GitHub
        uses: stefanzweifel/git-auto-commit-action@v4.6.0
        with:
          commit_message: amounts.csv updated
          file_pattern: amounts.csv
