name: Collect ActBlue ticker value

on:
  schedule:
    - cron: "*/15 * * * *" # every 15 minutes

jobs:
  scrape:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout the repo
      uses: actions/checkout@v4

    - name: Run scraper
      id: scraper
      run: ./scrape.sh

    - name: Commit sitewide_raised_amount.txt to GitHub
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Changed by ${{ env.difference }}
        file_pattern: sitewide_raised_amount.txt
