name: Prepare amounts.csv

on:
  schedule:
    - cron: "46 * * * *" # 46 minutes past the hour

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare CSV of amounts
        id: format
        run: ./format.sh

      - name: Commit amounts.csv to GitHub
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: amounts.csv updated
          file_pattern: amounts.csv
          skip_fetch: true
