name: Scrape ActBlue ticker

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Run scraper
        id: scraper
        run: ./scrape.sh

      - name: Commit to GitHub
        uses: stefanzweifel/git-auto-commit-action@v4.6
        with:
          commit_message: Changed by ${{ steps.scraper.outputs.difference }}
          file_pattern: sitewide_raised_amount.txt
